name: Release
on:
  release:
    types:
      - published

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]
        poetry-version: [1.8.2]
        os: [ubuntu-latest]
    environment:
      name: pypi
      url: https://pypi.org/p/svdi-cli
    permissions:
      id-token: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Build
        run: poetry build 
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
